# Generated by Django 4.1 on 2022-08-19 19:54

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MX', 'Mx.'), ('NONE', 'None')], default='NONE', max_length=4, verbose_name='title')),
                ('person_properties_freetext', models.CharField(blank=True, max_length=60, null=True, verbose_name='person properties freetext')),
                ('occupation', models.CharField(blank=True, max_length=50, null=True, verbose_name='occupation')),
                ('task_field_note', models.TextField(blank=True, max_length=300, null=True, verbose_name='task field note')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=8, null=True, verbose_name='street number')),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='postal code')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='address - city')),
                ('private_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='fixed telephone')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='mobile phone')),
                ('remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks')),
                ('only_job_related_topics', models.CharField(blank=True, choices=[('UNDEFINED', 'undefined'), ('ABSOLUTE', 'absolute'), ('NOTONLY', 'not only')], max_length=9, null=True, verbose_name='commitment only for job-related topics')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('activity_radius_km', models.IntegerField(blank=True, default=0, null=True, verbose_name='agreement to activity radius in km')),
            ],
            options={
                'verbose_name': 'registered helper',
                'verbose_name_plural': 'registered helpers',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('owner', models.CharField(choices=[('SELF', 'person itself'), ('ORG', 'provided by organization'), ('THIRDPARTY', 'other party')], default='ORG', max_length=10)),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'operation',
                'verbose_name_plural': 'operations',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='PersonProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('necessity', models.CharField(choices=[('RECOMMENDED', 'recommended'), ('MANDATORY', 'mandatory')], default='RECOMMENDED', max_length=11, verbose_name='necessity')),
            ],
            options={
                'verbose_name': 'person property',
                'verbose_name_plural': 'person properties',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('personal_hint', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=1, verbose_name='Amount of resources desirable with this role')),
                ('equipment_needed', models.ManyToManyField(blank=True, related_name='equipment_needed', to='georga.equipment')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('is_template', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TaskField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization')),
            ],
            options={
                'verbose_name': 'task field',
                'verbose_name_plural': 'task fields',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('postal_address_name', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_street', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_country', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('locations', models.ManyToManyField(blank=True, related_name='task_locations', to='georga.location')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.operation')),
                ('persons_participated', models.ManyToManyField(blank=True, related_name='persons_participated', to=settings.AUTH_USER_MODEL)),
                ('persons_registered', models.ManyToManyField(blank=True, related_name='persons_registered', to=settings.AUTH_USER_MODEL)),
                ('resources_desirable', models.ManyToManyField(blank=True, related_name='resources_desirable', to='georga.resource')),
                ('resources_required', models.ManyToManyField(blank=True, related_name='resources_required', to='georga.resource')),
                ('roles', models.ManyToManyField(blank=True, related_name='task_roles', to='georga.role')),
                ('task_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='georga.taskfield')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('CANCELED', 'canceled'), ('DELETED', 'deleted')], default='DRAFT', max_length=9)),
                ('enrollment_deadline', models.DateTimeField(default=datetime.datetime.now)),
                ('locations', models.ManyToManyField(related_name='shift_locations', to='georga.location')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.task')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='RoleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('person_properties', models.ManyToManyField(blank=True, related_name='person_properties', to='georga.personproperty')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='role',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.shift'),
        ),
        migrations.AddField(
            model_name='resource',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.shift'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='PersonToObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('unnoticed', models.BooleanField(default=True)),
                ('bookmarked', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['organization', 'project', 'operation', 'task', 'shift', 'message']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('person', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codename', models.CharField(default='', max_length=30, verbose_name='person propery group')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('selection_type', models.CharField(choices=[('MULTISELECT', 'multiselect'), ('SINGLESELECT', 'singleselect')], default='MULTISELECT', max_length=12, verbose_name='selection type')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization')),
            ],
            options={
                'verbose_name': 'group of person properties',
                'verbose_name_plural': 'groups of person properties',
            },
        ),
        migrations.AddField(
            model_name='personproperty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_property_group', to='georga.personpropertygroup'),
        ),
        migrations.AddField(
            model_name='personproperty',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.project'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('contents', models.CharField(max_length=1000)),
                ('priority', models.CharField(choices=[('DISTURB', 'disturb'), ('ONAPPCALL', 'on app call'), ('ONNEWS', 'on reading news actively')], default='ONNEWS', max_length=9)),
                ('category', models.CharField(choices=[('NEWS', 'news'), ('ALERT', 'alert'), ('ACTIVITY', 'activity')], default='NEWS', max_length=8)),
                ('state', models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], default='DRAFT', max_length=9)),
                ('delivery_state', models.CharField(choices=[('NONE', 'none'), ('PENDING', 'pending'), ('SENT', 'sent'), ('SENT_SUCCESSFULLY', 'sent successfully'), ('SENT_ERROR', 'sent error')], default='NONE', max_length=17)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['organization', 'project', 'operation', 'task', 'shift']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization')),
            ],
            options={
                'verbose_name': 'location category',
                'verbose_name_plural': 'location categories',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='location_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.locationcategory'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization'),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('device_string', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=35)),
                ('app_version', models.CharField(max_length=15)),
                ('push_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.organization')),
            ],
            options={
                'verbose_name': 'client device',
                'verbose_name_plural': 'client devices',
            },
        ),
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField()),
                ('acl_string', models.CharField(choices=[('ADMIN', 'admin')], default='ADMIN', max_length=5)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['organization', 'project', 'operation']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('person', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uuid')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='devices',
            field=models.ManyToManyField(blank=True, to='georga.device', verbose_name='devices'),
        ),
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='person',
            name='organizations_subscribed',
            field=models.ManyToManyField(to='georga.organization', verbose_name='organizations subscribed to'),
        ),
        migrations.AddField(
            model_name='person',
            name='person_properties',
            field=models.ManyToManyField(blank=True, to='georga.personproperty', verbose_name='person properties'),
        ),
        migrations.AddField(
            model_name='person',
            name='resources_provided',
            field=models.ManyToManyField(blank=True, to='georga.resource', verbose_name='resources provided'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles_agreed',
            field=models.ManyToManyField(blank=True, to='georga.role', verbose_name='agreement to roles'),
        ),
        migrations.AddField(
            model_name='person',
            name='task_fields_agreed',
            field=models.ManyToManyField(blank=True, to='georga.taskfield', verbose_name='agreement to task fields'),
        ),
        migrations.AddField(
            model_name='person',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='acl',
            index=models.Index(fields=['content_type', 'object_id'], name='georga_acl_content_cc2d2e_idx'),
        ),
    ]
