# Generated by Django 4.1 on 2022-09-26 18:51

from django.db import migrations
import georga.models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', georga.models.PersonManager()),
            ],
        ),
    ]
