# Generated by Django 3.2.14 on 2022-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationcategory',
            name='selection_type',
            field=models.CharField(choices=[('MULTISELECT', 'multiselect'), ('SINGLESELECT', 'singleselect')], default='MULTISELECT', max_length=12, verbose_name='selection type'),
        ),
    ]
