# Generated by Django 4.1.2 on 2022-11-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('person', 'role')},
        ),
    ]
