# Generated by Django 4.1.2 on 2022-11-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'participant', 'verbose_name_plural': 'participants'},
        ),
        migrations.AlterModelOptions(
            name='rolespecification',
            options={'verbose_name': 'role specificatioin', 'verbose_name_plural': 'role specifications'},
        ),
    ]
