# Generated by Django 4.0.3 on 2022-03-12 15:12

import datetime

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('call_for_volunteers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicationCategory',
        ),
        migrations.DeleteModel(
            name='SinglePersonUptime',
        ),
        migrations.RemoveField(
            model_name='person',
            name='available_for_cleaning',
        ),
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='company_phone_mobile',
        ),
        migrations.RemoveField(
            model_name='person',
            name='drk_employee',
        ),
        migrations.RemoveField(
            model_name='person',
            name='drk_home',
        ),
        migrations.RemoveField(
            model_name='person',
            name='drk_honorary',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emergency_opening_times',
        ),
        migrations.RemoveField(
            model_name='person',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='opening_times',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='person',
            name='position_in_company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='possible_work_times',
        ),
        migrations.AddField(
            model_name='person',
            name='password_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 15, 12, 39, 816025)),
        ),
        migrations.AlterField(
            model_name='person',
            name='help_operations',
            field=models.ManyToManyField(blank=True, to='call_for_volunteers.helpoperation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Mobilnummer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='private_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='Festnetznummer'),
        ),
        migrations.DeleteModel(
            name='GeneralWorkAvailability',
        ),
        migrations.DeleteModel(
            name='OpeningTime',
        ),
    ]
