# Generated by Django 4.2.11 on 2024-04-20 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personpropertygroup',
            name='codename',
        ),
    ]
