# Generated by Django 4.1 on 2022-08-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ACL',
            new_name='ACE',
        ),
        migrations.RenameField(
            model_name='ace',
            old_name='acl_string',
            new_name='ace_string',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_field',
            new_name='field',
        ),
        migrations.RenameIndex(
            model_name='ace',
            new_name='georga_ace_access__88e18a_idx',
            old_name='georga_acl_access__1249e9_idx',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_properties',
        ),
        migrations.RemoveField(
            model_name='personproperty',
            name='necessity',
        ),
        migrations.RemoveField(
            model_name='task',
            name='persons_participated',
        ),
        migrations.RemoveField(
            model_name='task',
            name='persons_registered',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postal_address_city',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postal_address_country',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postal_address_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postal_address_street',
        ),
        migrations.RemoveField(
            model_name='task',
            name='postal_address_zip_code',
        ),
        migrations.AddField(
            model_name='location',
            name='postal_address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_address_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_address_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_address_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postal_address_zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='properties',
            field=models.ManyToManyField(blank=True, to='georga.personproperty', verbose_name='properties'),
        ),
        migrations.AddField(
            model_name='personpropertygroup',
            name='necessity',
            field=models.CharField(choices=[('RECOMMENDED', 'recommended'), ('MANDATORY', 'mandatory'), ('NOT_POSSIBLE', 'not possible')], default='RECOMMENDED', max_length=12, verbose_name='necessity'),
        ),
        migrations.AddField(
            model_name='rolespecification',
            name='necessity',
            field=models.CharField(choices=[('RECOMMENDED', 'recommended'), ('MANDATORY', 'mandatory'), ('NOT_POSSIBLE', 'not possible')], default='RECOMMENDED', max_length=12, verbose_name='necessity'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_properties_freetext',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='properties freetext'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('CANCELED', 'canceled'), ('DELETED', 'deleted'), ('DONE', 'done')], default='DRAFT', max_length=9),
        ),
    ]
