# Generated by Django 4.1 on 2022-08-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delivery_state_email',
            field=models.CharField(choices=[('NONE', 'none'), ('PENDING', 'pending'), ('SENT', 'sent'), ('SENT_ERROR', 'sent error'), ('SENT_SUCCESSFULLY', 'sent successfully')], default='NONE', max_length=17),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_state_push',
            field=models.CharField(choices=[('NONE', 'none'), ('PENDING', 'pending'), ('SENT', 'sent'), ('SENT_ERROR', 'sent error'), ('SENT_SUCCESSFULLY', 'sent successfully')], default='NONE', max_length=17),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_state_sms',
            field=models.CharField(choices=[('NONE', 'none'), ('PENDING', 'pending'), ('SENT', 'sent'), ('SENT_ERROR', 'sent error'), ('SENT_SUCCESSFULLY', 'sent successfully')], default='NONE', max_length=17),
        ),
    ]
