# Generated by Django 4.1 on 2022-09-15 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='admin_acceptance_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants_decided', to=settings.AUTH_USER_MODEL),
        ),
    ]
