# Generated by Django 4.1 on 2022-09-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.taskfield'),
        ),
    ]
