# Generated by Django 4.1.2 on 2022-11-27 23:55

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0002_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='acceptance',
            field=django_fsm.FSMField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending')], max_length=8),
        ),
        migrations.AlterField(
            model_name='participant',
            name='admin_acceptance',
            field=django_fsm.FSMField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('NONE', 'None')], default='PENDING', max_length=8),
        ),
    ]
