# Generated by Django 4.1 on 2022-08-25 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0002_rename_acl_ace_rename_acl_string_ace_ace_string_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personproperty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.personpropertygroup'),
        ),
    ]
