# Generated by Django 4.1 on 2022-09-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0002_alter_task_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='operation',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('ARCHIVED', 'archived'), ('DELETED', 'deleted')], default='DRAFT', max_length=9),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('ARCHIVED', 'archived'), ('DELETED', 'deleted')], default='DRAFT', max_length=9),
        ),
        migrations.AddField(
            model_name='participant',
            name='acceptance',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('DECLINED', 'declined'), ('PENDING', 'pending')], default='ACCEPTED', max_length=8),
        ),
        migrations.AddField(
            model_name='participant',
            name='admin_acceptance',
            field=models.CharField(choices=[('ACCEPTED', 'accepted'), ('DECLINED', 'declined'), ('PENDING', 'pending'), ('NONE', 'none')], default='NONE', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('ARCHIVED', 'archived'), ('DELETED', 'deleted')], default='DRAFT', max_length=9),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='needs_admin_acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('ARCHIVED', 'archived'), ('DELETED', 'deleted')], default='DRAFT', max_length=9),
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('DELETED', 'deleted')], default='DRAFT', max_length=9),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rolespecification',
            name='necessity',
            field=models.CharField(choices=[('MANDATORY', 'mandatory'), ('RECOMMENDED', 'recommended'), ('UNRECOMMENDED', 'unrecommended'), ('IMPOSSIBLE', 'impossible')], max_length=13, verbose_name='necessity'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('FINISHED', 'finished'), ('CANCELED', 'canceled'), ('DELETED', 'deleted')], default='DRAFT', max_length=9),
        ),
    ]
