# Generated by Django 4.2.11 on 2024-04-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0002_remove_personpropertygroup_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personproperty',
            name='name',
            field=models.CharField(default='-', max_length=50),
            preserve_default=False,
        ),
    ]
