# Generated by Django 3.2.14 on 2022-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0002_qualificationcategory_selection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationcategory',
            name='code',
            field=models.CharField(default='', max_length=15, verbose_name='qualification category'),
        ),
    ]
