# Generated by Django 4.1 on 2022-08-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0003_alter_personproperty_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
