# Generated by Django 4.1.2 on 2022-11-28 00:16

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0003_alter_participant_acceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='admin_acceptance',
            field=django_fsm.FSMField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('NONE', 'None')], default='PENDING', max_length=8),
        ),
    ]
