# Generated by Django 3.2.14 on 2022-08-05 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0003_qualificationcategory_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='organization',
        ),
        migrations.AddField(
            model_name='deployment',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='georga.project'),
        ),
    ]
