# Generated by Django 3.2.13 on 2022-05-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0003_add_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('HERR', 'Herr'), ('FRAU', 'Frau'), ('DIVERS', 'Divers'), ('NONE', 'Keine')], default='NONE', max_length=6),
        ),
        migrations.AlterField(
            model_name='poll',
            name='style',
            field=models.CharField(choices=[('DEFAULT', 'default')], default='DEFAULT', max_length=20),
        ),
    ]
