# Generated by Django 3.2.14 on 2022-08-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0004_auto_20220805_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
