# Generated by Django 4.1 on 2022-08-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0004_organization_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='organizations_subscribed',
            field=models.ManyToManyField(blank=True, to='georga.organization', verbose_name='organizations subscribed to'),
        ),
    ]
