# Generated by Django 4.2.2 on 2023-07-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0004_alter_participant_admin_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
