# Generated by Django 3.2.13 on 2022-05-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0004_uppercase_choice_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Einsatzaktionstyp',
                'verbose_name_plural': 'Einsatzaktionstypen',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('device_string', models.CharField(max_length=50)),
                ('os_version', models.CharField(max_length=35)),
                ('app_version', models.CharField(max_length=15)),
                ('push_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Client-Gerät',
                'verbose_name_plural': 'Client-Geräte',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Trägerorganisation',
                'verbose_name_plural': 'Trägerorganisationen',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(max_length=50)),
                ('personal_hint', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressourcen',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Einsatzrolle',
                'verbose_name_plural': 'Einsatzrollen',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='activity_range_km',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='georga.organization')),
            ],
            options={
                'verbose_name': 'Einsatzprojekt',
                'verbose_name_plural': 'Einsatzprojekte',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('postal_address_name', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_street', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_country', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='georga.actiontype')),
                ('persons_participated', models.ManyToManyField(blank=True, related_name='persons_participated', to=settings.AUTH_USER_MODEL)),
                ('persons_registered', models.ManyToManyField(blank=True, related_name='persons_registered', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='georga.project')),
                ('resources_desirable', models.ManyToManyField(blank=True, related_name='resources_desirable', to='georga.Resource')),
                ('resources_required', models.ManyToManyField(blank=True, related_name='resources_required', to='georga.Resource')),
                ('roles_desirable', models.ManyToManyField(blank=True, related_name='roles_desirable', to='georga.Role')),
                ('roles_required', models.ManyToManyField(blank=True, related_name='roles_required', to='georga.Role')),
            ],
            options={
                'verbose_name': 'Einsatzaktion',
                'verbose_name_plural': 'Einsatzaktionen',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.device'),
        ),
        migrations.AddField(
            model_name='person',
            name='resources_provided',
            field=models.ManyToManyField(blank=True, to='georga.Resource'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, to='georga.Role'),
        ),
    ]
