# Generated by Django 4.1 on 2022-08-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0005_alter_person_organizations_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MS', 'Ms.'), ('MX', 'Mx.'), ('NONE', 'None')], default='NONE', max_length=4, verbose_name='title'),
        ),
    ]
