# Generated by Django 3.2.14 on 2022-08-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0005_alter_deployment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='deployment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='georga.deployment'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
