# Generated by Django 3.2.13 on 2022-06-26 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0005_actiontype_device_organization_resource_role_project_action'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionType',
            new_name='TaskCategory',
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'deployment',
                'verbose_name_plural': 'deployments',
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'location category',
                'verbose_name_plural': 'location categories',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('contents', models.CharField(max_length=1000)),
                ('priority', models.CharField(choices=[('DISTURB', 'disturb'), ('ONAPPCALL', 'on app call'), ('ONNEWS', 'on reading news actively')], default='ONNEWS', max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'notification category',
                'verbose_name_plural': 'notification categories',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('qualification_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.locationcategory')),
            ],
            options={
                'verbose_name': 'qualification',
                'verbose_name_plural': 'qualification',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'schedule',
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('postal_address_name', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_street', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address_country', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.schedule')),
            ],
            options={
                'verbose_name': 'timeslot',
                'verbose_name_plural': 'timeslots',
            },
        ),
        migrations.RenameModel(
            old_name='HelpOperation',
            new_name='QualificationCategory',
        ),
        migrations.RemoveField(
            model_name='action',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='persons_participated',
        ),
        migrations.RemoveField(
            model_name='action',
            name='persons_registered',
        ),
        migrations.RemoveField(
            model_name='action',
            name='project',
        ),
        migrations.RemoveField(
            model_name='action',
            name='resources_desirable',
        ),
        migrations.RemoveField(
            model_name='action',
            name='resources_required',
        ),
        migrations.RemoveField(
            model_name='action',
            name='roles_desirable',
        ),
        migrations.RemoveField(
            model_name='action',
            name='roles_required',
        ),
        migrations.DeleteModel(
            name='ActionCategory',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pollchoice',
            name='persons',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'client device', 'verbose_name_plural': 'client devices'},
        ),
        migrations.AlterModelOptions(
            name='equipmentprovided',
            options={'verbose_name': 'equipment provided by organization', 'verbose_name_plural': 'equipments provided by organization'},
        ),
        migrations.AlterModelOptions(
            name='equipmentself',
            options={'verbose_name': 'own equipment', 'verbose_name_plural': 'own equipments'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'registered helper', 'verbose_name_plural': 'registered helpers'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='qualificationcategory',
            options={'verbose_name': 'qualification category', 'verbose_name_plural': 'qualification categories'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelOptions(
            name='restriction',
            options={'verbose_name': 'restriction', 'verbose_name_plural': 'restrictions'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'task category', 'verbose_name_plural': 'task categories'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='activity_range_km',
        ),
        migrations.RemoveField(
            model_name='person',
            name='help_description',
        ),
        migrations.RemoveField(
            model_name='person',
            name='help_operations',
        ),
        migrations.RemoveField(
            model_name='person',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualifications_administrative',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualifications_health',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualifications_language',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualifications_license',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualifications_technical',
        ),
        migrations.RemoveField(
            model_name='person',
            name='roles',
        ),
        migrations.AddField(
            model_name='person',
            name='activity_radius_km',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='agreement to activity radius in km'),
        ),
        migrations.AddField(
            model_name='person',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='georga.Device', verbose_name='devices'),
        ),
        migrations.AddField(
            model_name='person',
            name='organizations_subscribed',
            field=models.ManyToManyField(to='georga.Organization', verbose_name='organizations subscribed to'),
        ),
        migrations.AddField(
            model_name='person',
            name='roles_agreed',
            field=models.ManyToManyField(blank=True, null=True, to='georga.Role', verbose_name='agreement to roles'),
        ),
        migrations.AddField(
            model_name='person',
            name='task_categories_agreed',
            field=models.ManyToManyField(blank=True, null=True, to='georga.TaskCategory', verbose_name='agreement to task categories'),
        ),
        migrations.AddField(
            model_name='person',
            name='task_category_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='task category details'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='address - city'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='mobile phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='street number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='only_job_related_topics',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'undefined'), ('ABSOLUTE', 'absolute'), ('NOTONLY', 'not only')], max_length=9, null=True, verbose_name='commitment only for job-related topics'),
        ),
        migrations.AlterField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='person',
            name='private_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, verbose_name='fixed telephone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='qualification_specific',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='qualification details'),
        ),
        migrations.AlterField(
            model_name='person',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='person',
            name='resources_provided',
            field=models.ManyToManyField(blank=True, null=True, to='georga.Resource', verbose_name='resources provided'),
        ),
        migrations.AlterField(
            model_name='person',
            name='restriction_specific',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='restriction details'),
        ),
        migrations.AlterField(
            model_name='person',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='georga.Restriction', verbose_name='restrictions'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('HERR', 'Herr'), ('FRAU', 'Frau'), ('DIVERS', 'Divers'), ('NONE', 'Keine')], default='NONE', max_length=6, verbose_name='title'),
        ),
        #migrations.RenameModel(
        #    old_name='ActionType',
        #    new_name='TaskCategory',
        #),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollChoice',
        ),
        migrations.DeleteModel(
            name='QualificationAdministrative',
        ),
        migrations.DeleteModel(
            name='QualificationHealth',
        ),
        migrations.DeleteModel(
            name='QualificationLanguage',
        ),
        migrations.DeleteModel(
            name='QualificationLicense',
        ),
        migrations.DeleteModel(
            name='QualificationTechnical',
        ),
        migrations.AddField(
            model_name='task',
            name='persons_participated',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='persons_registered',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='georga.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='resources_desirable',
            field=models.ManyToManyField(blank=True, null=True, related_name='resources_desirable', to='georga.Resource'),
        ),
        migrations.AddField(
            model_name='task',
            name='resources_required',
            field=models.ManyToManyField(blank=True, null=True, related_name='resources_required', to='georga.Resource'),
        ),
        migrations.AddField(
            model_name='task',
            name='roles_desirable',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles_desirable', to='georga.Role'),
        ),
        migrations.AddField(
            model_name='task',
            name='roles_required',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles_required', to='georga.Role'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='georga.taskcategory'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georga.task'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.notificationcategory'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='georga.organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='location_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.locationcategory'),
        ),
        migrations.AddField(
            model_name='person',
            name='qualifications',
            field=models.ManyToManyField(blank=True, to='georga.Qualification', verbose_name='qualification'),
        ),
    ]
