# Generated by Django 4.2.6 on 2023-10-24 15:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0005_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email_delivery',
            field=django_fsm.FSMField(choices=[('NONE', 'None'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='NONE', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='push_delivery',
            field=django_fsm.FSMField(choices=[('NONE', 'None'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='NONE', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sms_delivery',
            field=django_fsm.FSMField(choices=[('NONE', 'None'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='NONE', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='DRAFT', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='state',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='DRAFT', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='DRAFT', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='acceptance',
            field=django_fsm.FSMField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending')], max_length=8, protected=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='admin_acceptance',
            field=django_fsm.FSMField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('PENDING', 'Pending'), ('NONE', 'None')], default='PENDING', max_length=8, protected=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='DRAFT', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='state',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('FINISHED', 'Finished'), ('CANCELED', 'Canceled'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='DRAFT', max_length=9, protected=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='DRAFT', max_length=9, protected=True),
        ),
    ]
