# Generated by Django 3.2.13 on 2022-06-26 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0006_auto_20220626_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'task category', 'verbose_name_plural': 'task categories'},
        ),
        migrations.AlterField(
            model_name='person',
            name='devices',
            field=models.ManyToManyField(blank=True, to='georga.Device', verbose_name='devices'),
        ),
        migrations.AlterField(
            model_name='person',
            name='resources_provided',
            field=models.ManyToManyField(blank=True, to='georga.Resource', verbose_name='resources provided'),
        ),
        migrations.AlterField(
            model_name='person',
            name='roles_agreed',
            field=models.ManyToManyField(blank=True, to='georga.Role', verbose_name='agreement to roles'),
        ),
        migrations.AlterField(
            model_name='person',
            name='task_categories_agreed',
            field=models.ManyToManyField(blank=True, to='georga.TaskCategory', verbose_name='agreement to task categories'),
        ),
        migrations.AlterField(
            model_name='task',
            name='persons_participated',
            field=models.ManyToManyField(blank=True, related_name='persons_participated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='persons_registered',
            field=models.ManyToManyField(blank=True, related_name='persons_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='resources_desirable',
            field=models.ManyToManyField(blank=True, related_name='resources_desirable', to='georga.Resource'),
        ),
        migrations.AlterField(
            model_name='task',
            name='resources_required',
            field=models.ManyToManyField(blank=True, related_name='resources_required', to='georga.Resource'),
        ),
        migrations.AlterField(
            model_name='task',
            name='roles_desirable',
            field=models.ManyToManyField(blank=True, related_name='roles_desirable', to='georga.Role'),
        ),
        migrations.AlterField(
            model_name='task',
            name='roles_required',
            field=models.ManyToManyField(blank=True, related_name='roles_required', to='georga.Role'),
        ),
    ]
