# Generated by Django 3.2.14 on 2022-08-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0007_alter_task_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcategory',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
