# Generated by Django 4.1 on 2022-08-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0007_rename_title_task_name_operation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='task',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='task',
            name='roles',
        ),
        migrations.AddField(
            model_name='shift',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georga.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georga.location'),
        ),
        migrations.AddField(
            model_name='task',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georga.role'),
        ),
    ]
