# Generated by Django 4.1 on 2022-08-29 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0008_remove_shift_locations_remove_task_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='task',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='task',
            name='roles',
        ),
        migrations.AddField(
            model_name='location',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.shift'),
        ),
        migrations.AddField(
            model_name='location',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.task'),
        ),
        migrations.AddField(
            model_name='role',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='georga.task'),
        ),
    ]
