# Generated by Django 3.2.14 on 2022-08-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0008_alter_taskcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
