# Generated by Django 3.2.14 on 2022-08-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0009_schedule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
