# Generated by Django 4.2.11 on 2024-04-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0009_device_deleted_equipment_deleted_location_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
            ],
        ),
    ]
