# Generated by Django 3.2.14 on 2022-08-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0010_auto_20220806_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentprovided',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipmentself',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
