# Generated by Django 4.1 on 2022-09-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0010_alter_ace_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='organizations_employed',
            field=models.ManyToManyField(blank=True, related_name='persons_employed', to='georga.organization', verbose_name='organizations employed at'),
        ),
        migrations.AlterField(
            model_name='person',
            name='organizations_subscribed',
            field=models.ManyToManyField(blank=True, related_name='persons_subscribed', to='georga.organization', verbose_name='organizations subscribed to'),
        ),
    ]
