# Generated by Django 4.1 on 2022-09-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0012_ace_created_at_ace_updated_at_device_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ace',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='locationcategory',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='personproperty',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='personpropertygroup',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='persontoobject',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='rolespecification',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='taskfield',
            old_name='updated_at',
            new_name='modified_at',
        ),
    ]
