# Generated by Django 3.2.14 on 2022-08-07 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0013_auto_20220807_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='roles_desirable',
        ),
        migrations.RemoveField(
            model_name='task',
            name='roles_required',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='schedule',
        ),
        migrations.AddField(
            model_name='task',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='task_locations', to='georga.Location'),
        ),
        migrations.AddField(
            model_name='task',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='task_roles', to='georga.Role'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='enrollment_deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='locations',
            field=models.ManyToManyField(related_name='timeslot_locations', to='georga.Location'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='timeslot_roles', to='georga.Role'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('CANCELED', 'canceled'), ('DELETED', 'deleted')], default='DRAFT', max_length=9),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
