# Generated by Django 3.2.14 on 2022-08-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0014_auto_20220807_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amount of people desirable with this role'),
        ),
    ]
