# Generated by Django 4.1 on 2022-09-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0015_remove_task_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_category',
            new_name='category',
        ),
    ]
