# Generated by Django 4.1 on 2022-08-12 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0017_alter_deployment_uuid_alter_device_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('necessity', models.CharField(choices=[('RECOMMENDED', 'recommended'), ('MANDATORY', 'mandatory')], default='RECOMMENDED', max_length=11, verbose_name='necessity')),
            ],
            options={
                'verbose_name': 'person property',
                'verbose_name_plural': 'person properties',
            },
        ),
        migrations.CreateModel(
            name='PersonPropertyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codename', models.CharField(default='', max_length=15, verbose_name='person propery group')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('selection_type', models.CharField(choices=[('MULTISELECT', 'multiselect'), ('SINGLESELECT', 'singleselect')], default='MULTISELECT', max_length=12, verbose_name='selection type')),
            ],
            options={
                'verbose_name': 'group of person properties',
                'verbose_name_plural': 'groups of person properties',
            },
        ),
        migrations.RenameModel(
            old_name='Deployment',
            new_name='Operation',
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': 'operation', 'verbose_name_plural': 'operations'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='deployment',
            new_name='operation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualification_specific',
        ),
        migrations.RemoveField(
            model_name='person',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='person',
            name='restriction_specific',
        ),
        migrations.RemoveField(
            model_name='person',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='qualifications_suitable',
        ),
        migrations.AddField(
            model_name='person',
            name='person_properties_freetext',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='person properties freetext'),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='QualificationCategory',
        ),
        migrations.DeleteModel(
            name='Restriction',
        ),
        migrations.AddField(
            model_name='personproperty',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_property_group', to='georga.personpropertygroup'),
        ),
        migrations.AddField(
            model_name='person',
            name='person_properties',
            field=models.ManyToManyField(blank=True, to='georga.personproperty', verbose_name='person properties'),
        ),
        migrations.AddField(
            model_name='role',
            name='person_properties',
            field=models.ManyToManyField(blank=True, related_name='person_properties', to='georga.personproperty'),
        ),
    ]
