# Generated by Django 4.1 on 2022-08-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0019_device_organization_equipment_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpropertygroup',
            name='codename',
            field=models.CharField(default='', max_length=30, verbose_name='person propery group'),
        ),
    ]
