# Generated by Django 4.1 on 2022-08-12 22:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0020_alter_personpropertygroup_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('person_properties', models.ManyToManyField(blank=True, related_name='person_properties', to='georga.personproperty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published'), ('CANCELED', 'canceled'), ('DELETED', 'deleted')], default='DRAFT', max_length=9)),
                ('enrollment_deadline', models.DateTimeField(default=datetime.datetime.now)),
                ('locations', models.ManyToManyField(related_name='shift_locations', to='georga.location')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
            },
        ),
        migrations.RenameModel(
            old_name='TaskCategory',
            new_name='TaskField',
        ),
        migrations.AlterModelOptions(
            name='taskfield',
            options={'verbose_name': 'task field', 'verbose_name_plural': 'task fields'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_category',
            new_name='task_field',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='person',
            name='task_categories_agreed',
        ),
        migrations.RemoveField(
            model_name='person',
            name='task_category_description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='role',
            name='person_properties',
        ),
        migrations.RemoveField(
            model_name='task',
            name='organization',
        ),
        migrations.AddField(
            model_name='person',
            name='task_field_note',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='task field note'),
        ),
        migrations.AddField(
            model_name='person',
            name='task_fields_agreed',
            field=models.ManyToManyField(blank=True, to='georga.taskfield', verbose_name='agreement to task fields'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='operation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.operation'),
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
        migrations.AddField(
            model_name='shift',
            name='roles',
            field=models.ManyToManyField(related_name='shift_roles', to='georga.role'),
        ),
        migrations.AddField(
            model_name='shift',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.task'),
        ),
        migrations.AddField(
            model_name='rolespecification',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.shift'),
        ),
    ]
