# Generated by Django 4.1 on 2022-08-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0021_rolespecification_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='roles',
        ),
        migrations.AddField(
            model_name='resource',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount of resources desirable with this role'),
        ),
        migrations.AddField(
            model_name='resource',
            name='shift',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.shift'),
        ),
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount of people desirable with this role'),
        ),
    ]
