# Generated by Django 4.1 on 2022-08-13 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('georga', '0023_persontoobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='amount',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('person', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='georga.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
